[prune]
  unused-packages = true
  non-go = true
  go-tests = true

[[constraint]]
  name = "github.com/fsouza/go-dockerclient"
  version = "v1.3.0"

[[override]]
  name = "github.com/docker/docker"
  branch = "master"

[[override]]	
  name = "github.com/docker/distribution"	
  revision = "master"

[[override]]
  name = "github.com/docker/libnetwork"
  branch = "master"

[[constraint]]
  name = "github.com/nightlyone/lockfile"
  revision = "0ad87eef1443f64d3d8c50da647e2b1552851124"

[[constraint]]
  name = "github.com/pmezard/go-difflib"
  version = "1.0.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "github.com/google/go-containerregistry"
  revision = "bada66e31e55b96029f4e456f8eb107f58319629"
