# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

# Implicit dependency of github.com/fsouza/go-dockerclient, which depends on 
# github.com/docker/docker, which depends on github.com/docker/distribution.
# Since this is vendored through something other than dep, dep doesn't know
# how to resolve it, so we have to do it manually.
required = ["github.com/docker/distribution"]
[[constraint]]
  name = "github.com/docker/distribution"
  revision = "f0cc927784781fa395c06317c58dea2841ece3a9"

[[constraint]]
  name = "github.com/fsouza/go-dockerclient"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/nightlyone/lockfile"

[[constraint]]
  name = "github.com/pmezard/go-difflib"
  version = "1.0.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "github.com/google/go-containerregistry"
  revision = "dc0a77702ddab8c3dc5630eca7c026d571c1c9b7"
